baseURL = "/"
languageCode = "it"
title = "Silvio Buscato"
theme = "hugo-sb"
summaryLength = "20"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Tutti gli articoli"
    url = "/blog/"
    weight = 1

    [[menu.main]]
    identifier = "about"
    name = "Chi sono"
    title = "Chi sono"
    url = "/about/"
    weight = 2


